name = "lasimple"
license = "MIT"
licenselink = "https://github.com/jbub/ghostwriter/blob/master/LICENSE.md"
description = "A simple Hugo theme inspired from ghostwriter theme"
min_version = 0.15

#[author]
#  name = "Laurent Aphecetche"

#  homepage = "https://github.com/aphecetche"
