title = "Laurent Aphecetche"
baseurl = "http://aphecetche.github.io/"
theme = "ghostwriter"
languageCode = "en-US"
copyright = "Laurent Aphecetche"

[Author]
    name = "Laurent Aphecetche"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    github = "https://github.com/aphecetche"
    headline = "Investigating High Energy Collisions"

[Permalinks]
  post = "/:filename/"

#    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "SAF3 User Manual"
    url = "/project/saf/usermanual"
    weight = 1

[[menu.main]]
        name = "Reco on SAF3"
        url = "/project/saf/saf3reco"
        weight = 1
