title = "High Energy Collisions Investigations"
baseurl = "http://aphecetche.github.io/"
theme = "lasimple"
languageCode = "en-US"
copyright = "Laurent Aphecetche"
buildDrafts = false

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true

[Author]
    name = "Laurent Aphecetche"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    github = "https://github.com/aphecetche"
#    headline = "Investigating High Energy Collisions"

[Permalinks]
  post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "SAF3 User Manual"
    url = "/saf3-usermanual"
    weight = 1

[[menu.main]]
    name = "Reco on SAF3"
    url = "/saf3-reco"
    weight = 2

[[menu.main]]
  name = "talks"
  url = "/talk"
  weight = 3
