title = "Laurent Aphecetche - High Energy Collisions Investigator"
baseurl = "http://aphecetche.github.io/"
theme = "lasimple"
languageCode = "en-US"
copyright = "Laurent Aphecetche"
buildDrafts = false

[Author]
    name = "Laurent Aphecetche"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    github = "https://github.com/aphecetche"
#    headline = "Investigating High Energy Collisions"

[Permalinks]
  post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "SAF3 User Manual"
    url = "/saf3-usermanual"
    weight = 1

[[menu.main]]
    name = "Reco on SAF3"
    url = "/saf3-reco"
    weight = 1
