title = "High Energy Collisions Investigations"
baseurl = "http://aphecetche.github.io/"
theme = "lasimple"
languageCode = "en-US"
copyright = "Laurent Aphecetche"
buildDrafts = false

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true

[Author]
    name = "Laurent Aphecetche"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    github = "https://github.com/aphecetche"
#    headline = "Investigating High Energy Collisions"

[Permalinks]
  post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "aliroot"
    url = "/#aliroot"
    weight = 1

[[menu.main]]
    name = "o2"
    url = "/#o2"
    weight = 2

[[menu.main]]
  name = "saf"
  url = "/#saf"
  weight = 3

[[menu.main]]
  name = "talks"
  url = "/#talks"
  weight = 4

[[menu.main]]
  name = "geek"
  url = "/#geek"
  weight = 5

