[build]
publish = "public"
command = "npm run build https://aphecetche.netlify.com/"

[context.production.environment]
HUGO_VERSION = "0.78.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]

[context.branch-deploy.environment]
HUGO_VERSION = "0.78.2"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

